### PR TITLE
Zezzy mad

### PR DESCRIPTION
**Pull request by jQueryBase64MyAss**

### CODE REVIEW

**Comment by zezzy** [comment]
ty

**Comment by Antr4xSoft** [comment]
Im a noob, already suffering from compiling errors. if anyone can help me, i would hugely appreciate.

skype: ons_o123

PLEASE HELP ME

**Comment by jQueryBase64MyAss** [comment]
@dz191 will add and help you

**Comment by DZ191** [comment]
Start by not copy pasting the whole sharpshooter structure and writing your own :+1: :smile:

**Comment by Antr4xSoft** [comment]
copy pasting sharpshooter was cuz my own code didnt work, i wanted to see if his code work. but it both seems to not work cuz of some kind of weird error. i have not tried to copy and paste other's code and claim that it is mine

**Comment by Antr4xSoft** [comment]
i cant even start coding anything cuz i cant even install it lol. please. anyone borrow me 10 min of their life to resolve this shit that has been bugging me for the last 8 hours?

**Comment by HoesLeaguesharp** [comment]
Add me: epvp.tears ill try to help

**Pull request merged**
